export function codexAuthsCard() {
  return [
    '<div class="card span-12">',
    '  <div class="head">',
    '    <h2>ChatGPT Codex auths</h2>',
    '    <span id="codex-auths-status" class="meta">multi-account profiles persisted in <code id="codex-auths-path">~/.shimex/codex-auths.json</code></span>',
    '  </div>',
    '  <div class="actions" id="codex-auths-actions">',
    '    <div class="action">',
    '      <div class="copy">',
    '        <div class="t">Sign in with OpenAI Codex</div>',
    '        <div class="d">Run the OpenAI Codex device-code flow inside Shimex. A new tab opens, you confirm on chatgpt.com, and the credentials are saved here under the chosen profile name.</div>',
    '      </div>',
    '      <div class="button-row">',
    '        <input id="codex-auths-device-name" type="text" placeholder="profile name (e.g. personal)" autocomplete="off" style="min-width:160px;" />',
    '        <button class="primary" id="codex-auths-device-start" type="button">Sign in</button>',
    '      </div>',
    '    </div>',
    '    <details class="action">',
    '      <summary><strong>Paste OAuth JSON</strong> <span class="muted" style="color:var(--muted); font-size:12px;"> (alternative for headless servers)</span></summary>',
    '      <div style="display:grid; gap:10px; margin-top:10px;">',
    '        <input id="codex-auths-paste-name" type="text" placeholder="profile name" autocomplete="off" />',
    '        <textarea id="codex-auths-paste-json" placeholder=\'{"tokens": {"access_token": "...", "refresh_token": "...", "expires": 1735689600, "account_id": "..."}}\' rows="6" style="font-family:ui-monospace,monospace;font-size:12px;padding:10px;border-radius:6px;border:1px solid var(--border-strong);background:var(--panel-2);color:var(--text);"></textarea>',
    '        <div class="button-row">',
    '          <button class="ghost" id="codex-auths-paste-save" type="button">Save JSON as profile</button>',
    '        </div>',
    '        <small style="color:var(--muted);">Tokens stay in <code>~/.shimex/codex-auths.json</code> on this machine. Shimex never logs them.</small>',
    '      </div>',
    '    </details>',
    '  </div>',
    '  <div style="overflow-x:auto; margin-top:14px;">',
    '    <table>',
    '      <thead>',
    '        <tr>',
    '          <th>Status</th>',
    '          <th>Profile</th>',
    '          <th>Updated</th>',
    '          <th>Token</th>',
    '          <th>Usage</th>',
    '          <th>Actions</th>',
    '        </tr>',
    '      </thead>',
    '      <tbody id="codex-auths-rows">',
    '        <tr><td colspan="6"><div class="skeleton" style="width:60%"></div></td></tr>',
    '      </tbody>',
    '    </table>',
    '  </div>',
    '</div>',
  ].join('\n');
}

export function codexAuthsRuntimeHelpers() {
  return [
    "    const codexAuthsEls = {};",
    "    const codexAuthsState = { profiles: [], defaultProfile: '', path: '', usage: {} };",
    "    function initCodexAuths() {",
    "      codexAuthsEls.rows = document.getElementById('codex-auths-rows');",
    "      codexAuthsEls.path = document.getElementById('codex-auths-path');",
    "      codexAuthsEls.status = document.getElementById('codex-auths-status');",
    "      codexAuthsEls.deviceName = document.getElementById('codex-auths-device-name');",
    "      codexAuthsEls.deviceStart = document.getElementById('codex-auths-device-start');",
    "      codexAuthsEls.pasteName = document.getElementById('codex-auths-paste-name');",
    "      codexAuthsEls.pasteJson = document.getElementById('codex-auths-paste-json');",
    "      codexAuthsEls.pasteSave = document.getElementById('codex-auths-paste-save');",
    "      codexAuthsEls.deviceStart.addEventListener('click', startCodexDeviceLogin);",
    "      codexAuthsEls.pasteSave.addEventListener('click', savePastedCodexAuth);",
    "      loadCodexAuths();",
    "    }",
    "    async function startCodexDeviceLogin() {",
    "      const profile = (codexAuthsEls.deviceName.value || '').trim();",
    "      try {",
    "        const response = await fetch('/api/codex-auths/start-device', {",
    "          method: 'POST',",
    "          headers: { 'content-type': 'application/json' },",
    "          body: JSON.stringify(profile ? { profile: profile } : {}),",
    "        });",
    "        const result = await parseJson(response);",
    "        if (!response.ok) {",
    "          toast('Codex device login failed to start', (result && result.error) || ('HTTP ' + response.status), 'err');",
    "          return;",
    "        }",
    "        if (!result.device || !result.device.id) {",
    "          toast('Codex device login failed to start', 'missing device id', 'err');",
    "          return;",
    "        }",
    "        window.open('/admin/codex-auth/device?id=' + encodeURIComponent(result.device.id), '_blank', 'noopener');",
    "        toast('Codex device login started', result.device.userCode, 'ok');",
    "      } catch (error) {",
    "        toast('Codex device login failed to start', String((error && error.message) || error), 'err');",
    "      }",
    "    }",
    "    async function savePastedCodexAuth() {",
    "      const profile = (codexAuthsEls.pasteName.value || '').trim();",
    "      const text = codexAuthsEls.pasteJson.value.trim();",
    "      if (!profile) { toast('Save failed', 'Enter a profile name first.', 'err'); return; }",
    "      if (!text) { toast('Save failed', 'Paste OAuth JSON first.', 'err'); return; }",
    "      let payload;",
    "      try { payload = JSON.parse(text); } catch (error) { toast('Save failed', 'Invalid JSON: ' + (error && error.message || error), 'err'); return; }",
    "      try {",
    "        const response = await fetch('/api/codex-auths', {",
    "          method: 'POST',",
    "          headers: { 'content-type': 'application/json' },",
    "          body: JSON.stringify({ name: profile, auth_json: text, label: payload && payload.label || profile }),",
    "        });",
    "        const result = await parseJson(response);",
    "        if (!response.ok) {",
    "          toast('Save failed', (result && result.error) || ('HTTP ' + response.status), 'err');",
    "          return;",
    "        }",
    "        toast('Saved', result.profile && result.profile.name || profile, 'ok');",
    "        codexAuthsEls.pasteJson.value = '';",
    "        await loadCodexAuths();",
    "      } catch (error) {",
    "        toast('Save failed', String((error && error.message) || error), 'err');",
    "      }",
    "    }",
    "    async function fetchCodexUsage(name) {",
    "      try {",
    "        const response = await fetch('/api/codex-auths/' + encodeURIComponent(name) + '/usage');",
    "        const result = await parseJson(response);",
    "        if (!response.ok) return { error: (result && result.error) || ('HTTP ' + response.status) };",
    "        return result;",
    "      } catch (error) {",
    "        return { error: String((error && error.message) || error) };",
    "      }",
    "    }",
    "    function fmtDateTime(value) {",
    "      if (!value) return '\\u2014';",
    "      var date = new Date(value);",
    "      if (Number.isNaN(date.getTime())) return value;",
    "      return date.toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });",
    "    }",
    "    function fmtReset(window) {",
    "      if (!window || !window.resetAtIso) return '';",
    "      return 'resets ' + fmtDateTime(window.resetAtIso);",
    "    }",
    "    function fmtUsageWindow(label, window) {",
    "      if (!window) return '';",
    "      var remaining = window.remainingPercent == null ? '?' : Math.round(window.remainingPercent) + '%';",
    "      return '<div><strong>' + escapeHtml(label) + ': ' + escapeHtml(remaining) + ' left</strong>' +",
    "        (window.usedPercent == null ? '' : ' <small style=\"color:var(--muted);\">(' + escapeHtml(Math.round(window.usedPercent) + '% used') + ')</small>') +",
    "        (window.resetAtIso ? '<div style=\"color:var(--muted); font-size:11px; margin-top:2px;\">' + escapeHtml(fmtReset(window)) + '</div>' : '') + '</div>';",
    "    }",
    "    function tokenCell(profile) {",
    "      if (!profile.expiresAt) return '<span class=\"badge text\">unknown</span>';",
    "      var cls = profile.tokenExpired ? 'danger' : 'ok';",
    "      var label = profile.tokenExpired ? 'expired' : 'valid';",
    "      var prefix = profile.tokenExpired ? 'expired ' : 'until ';",
    "      return '<span class=\"badge ' + cls + '\">' + label + '</span><div style=\"color:var(--muted); font-size:11px; margin-top:4px;\">' + escapeHtml(prefix + fmtDateTime(profile.expiresAt)) + '</div>';",
    "    }",
    "    function usageCell(profile) {",
    "      var usage = codexAuthsState.usage[profile.name];",
    "      if (!usage) return '<button class=\"ghost\" data-usage=\"' + escapeHtml(profile.name) + '\" type=\"button\">Probe</button>';",
    "      if (usage.error) return '<span class=\"badge text\" title=\"' + escapeHtml(usage.error) + '\">error</span>';",
    "      var bits = [];",
    "      if (usage.planType) bits.push('<span class=\"badge provider\">' + escapeHtml(usage.planType) + '</span>');",
    "      if (usage.limitReached) bits.push('<span class=\"badge danger\">limit reached</span>');",
    "      if (usage.primaryWindow) bits.push(fmtUsageWindow('5h', usage.primaryWindow));",
    "      if (usage.secondaryWindow) bits.push(fmtUsageWindow('weekly', usage.secondaryWindow));",
    "      var balance = usage.credits && usage.credits.balance !== '' ? usage.credits.balance : (usage.resetCreditsAvailable == null ? '?' : usage.resetCreditsAvailable);",
    "      bits.push('<div style=\"color:var(--muted); font-size:11px; margin-top:4px;\">credits: ' + escapeHtml(balance) + '</div>');",
    "      return bits.join('<div style=\"height:4px\"></div>');",
    "    }",
    "    function renderCodexAuths() {",
    "      if (codexAuthsState.path) codexAuthsEls.path.textContent = codexAuthsState.path;",
    "      if (codexAuthsState.status) {",
    "        const label = codexAuthsState.profiles.length",
    "          ? codexAuthsState.profiles.length + ' profile' + (codexAuthsState.profiles.length === 1 ? '' : 's') + ' / ' + (codexAuthsState.defaultProfile ? 'default: ' + codexAuthsState.defaultProfile : 'no default')",
    "          : 'no profiles yet';",
    "        codexAuthsEls.status.textContent = 'multi-account profiles persisted in ' + (codexAuthsEls.path.textContent || '~/.shimex/codex-auths.json') + ' — ' + label;",
    "      }",
    "      if (!codexAuthsState.profiles.length) {",
    "        codexAuthsEls.rows.innerHTML = '<tr><td colspan=\"6\"><div class=\"empty\">No Codex auth profiles yet. Use Sign in, paste JSON, or run <code>shimex codex-auth add &lt;name&gt;</code>.</div></td></tr>';",
    "        return;",
    "      }",
    "      codexAuthsEls.rows.innerHTML = codexAuthsState.profiles.map(function (profile) {",
    "        var statusCell = profile.available === false",
    "          ? '<span class=\"badge text\">unavailable</span>'",
    "          : (profile.tokenExpired ? '<span class=\"badge danger\">expired</span>' : '<span class=\"badge ok\">connected</span>');",
    "        var actions = [",
    "          '<button class=\"ghost\" data-rename=\"' + profile.name + '\" type=\"button\">Rename</button>',",
    "          '<button class=\"ghost\" data-use=\"' + profile.name + '\" type=\"button\"' + (profile.isDefault ? ' disabled' : '') + '>' + (profile.isDefault ? 'Default' : 'Make default') + '</button>',",
    "          '<button class=\"danger\" data-remove=\"' + profile.name + '\" type=\"button\">Disconnect</button>',",
    "        ].join(' ');",
    "        return [",
    "          '<tr>',",
    "          '  <td>' + statusCell + '</td>',",
    "          '  <td><code>' + profile.name + '</code>'",
    "            + (profile.label && profile.label !== profile.name ? '<div style=\"color:var(--muted); font-size:12px; margin-top:2px;\">' + profile.label + '</div>' : '')",
    "            + (profile.isDefault ? '<div style=\"font-size:11px; color:var(--accent); margin-top:2px;\">default profile</div>' : '')",
    "            + '</td>',",
    "          '  <td>' + escapeHtml(fmtDateTime(profile.updatedAt)) + '</td>',",
    "          '  <td>' + tokenCell(profile) + '</td>',",
    "          '  <td>' + usageCell(profile) + '</td>',",
    "          '  <td>' + actions + '</td>',",
    "          '</tr>',",
    "        ].join('\\n');",
    "      }).join('');",
    "      var probeButtons = codexAuthsEls.rows.querySelectorAll('button[data-usage]');",
    "      for (var i = 0; i < probeButtons.length; i++) {",
    "        probeButtons[i].addEventListener('click', async function () {",
    "          var name = this.getAttribute('data-usage');",
    "          this.disabled = true;",
    "          this.textContent = 'Probing\\u2026';",
    "          var result = await fetchCodexUsage(name);",
    "          codexAuthsState.usage[name] = result;",
    "          renderCodexAuths();",
    "        });",
    "      }",
    "      var renameButtons = codexAuthsEls.rows.querySelectorAll('button[data-rename]');",
    "      for (var r = 0; r < renameButtons.length; r++) {",
    "        renameButtons[r].addEventListener('click', async function () {",
    "          var name = this.getAttribute('data-rename');",
    "          var next = window.prompt('Rename Codex auth profile \\u201c' + name + '\\u201d to:', name);",
    "          if (!next || next === name) return;",
    "          try {",
    "            var response = await fetch('/api/codex-auths/' + encodeURIComponent(name) + '/rename', {",
    "              method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: next })",
    "            });",
    "            var result = await parseJson(response);",
    "            if (!response.ok) { toast('Rename failed', (result && result.error) || ('HTTP ' + response.status), 'err'); return; }",
    "            if (codexAuthsState.usage[name]) { codexAuthsState.usage[result.to || next] = codexAuthsState.usage[name]; delete codexAuthsState.usage[name]; }",
    "            toast('Renamed profile', name + ' \\u2192 ' + (result.to || next), 'ok');",
    "            await loadCodexAuths();",
    "          } catch (error) {",
    "            toast('Rename failed', String((error && error.message) || error), 'err');",
    "          }",
    "        });",
    "      }",
    "      var useButtons = codexAuthsEls.rows.querySelectorAll('button[data-use]');",
    "      for (var j = 0; j < useButtons.length; j++) {",
    "        useButtons[j].addEventListener('click', async function () {",
    "          var name = this.getAttribute('data-use');",
    "          try {",
    "            var response = await fetch('/api/codex-auths/' + encodeURIComponent(name) + '/use', { method: 'POST' });",
    "            var result = await parseJson(response);",
    "            if (!response.ok) { toast('Use failed', (result && result.error) || ('HTTP ' + response.status), 'err'); return; }",
    "            toast('Default profile', result.defaultProfile || name, 'ok');",
    "            await loadCodexAuths();",
    "          } catch (error) {",
    "            toast('Use failed', String((error && error.message) || error), 'err');",
    "          }",
    "        });",
    "      }",
    "      var removeButtons = codexAuthsEls.rows.querySelectorAll('button[data-remove]');",
    "      for (var k = 0; k < removeButtons.length; k++) {",
    "        removeButtons[k].addEventListener('click', async function () {",
    "          var name = this.getAttribute('data-remove');",
    "          if (!window.confirm('Disconnect Codex auth profile \\u201c' + name + '\\u201d?')) return;",
    "          try {",
    "            var response = await fetch('/api/codex-auths/' + encodeURIComponent(name), { method: 'DELETE' });",
    "            var result = await parseJson(response);",
    "            if (!response.ok) { toast('Disconnect failed', (result && result.error) || ('HTTP ' + response.status), 'err'); return; }",
    "          toast('Disconnected', name, 'ok');",
    "          await loadCodexAuths();",
    "          } catch (error) {",
    "            toast('Disconnect failed', String((error && error.message) || error), 'err');",
    "          }",
    "        });",
    "      }",
    "    }",
    "    async function loadCodexAuths() {",
    "      try {",
    "        var response = await fetch('/api/codex-auths');",
    "        var result = await parseJson(response);",
    "        if (!response.ok) {",
    "          codexAuthsEls.rows.innerHTML = '<tr><td colspan=\"6\"><div class=\"empty\">Could not load Codex auths: ' + ((result && result.error) || ('HTTP ' + response.status)) + '</div></td></tr>';",
    "          return;",
    "        }",
    "        codexAuthsState.profiles = result.profiles || [];",
    "        codexAuthsState.defaultProfile = result.defaultProfile || '';",
    "        codexAuthsState.path = result.path || '';",
    "        renderCodexAuths();",
    "      } catch (error) {",
    "        codexAuthsEls.rows.innerHTML = '<tr><td colspan=\"6\"><div class=\"empty\">Could not load Codex auths: ' + ((error && error.message) || error) + '</div></td></tr>';",
    "      }",
    "    }",
  ].join('\n');
}
