export function codexAuthsCard() {
  return [
    '<div class="auth-panel span-12" id="codex-auths-panel">',
    '  <div class="head">',
    '    <h2 id="codex-auths-title">Codex connected profiles<span class="auth-count"></span></h2>',
    '    <div style="display:flex; align-items:center; gap:10px;">',
    '      <span id="codex-auths-status" class="meta">multi-account profiles persisted in <code id="codex-auths-path">~/.shimex/codex-auths.json</code></span>',
    '      <button class="auth-refresh" id="codex-auths-refresh" type="button" title="Re-probe usage for all profiles"><span class="spin"></span>Refresh</button>',
    '    </div>',
    '  </div>',
    '  <div class="auth-signin" id="codex-auths-actions">',
    '    <div class="copy">',
    '      <div class="icon">C</div>',
    '      <div><div class="t">Sign in with OpenAI Codex</div><div class="d">Run the OpenAI Codex device-code flow inside Shimex. A new tab opens, you confirm on chatgpt.com, and the credentials are saved here under the chosen profile name.</div></div>',
    '    </div>',
    '    <div class="button-row">',
    '      <input id="codex-auths-device-name" type="text" placeholder="profile name (e.g. personal)" autocomplete="off" />',
    '      <button class="primary" id="codex-auths-device-start" type="button">Sign in</button>',
    '    </div>',
    '  </div>',
    '  <details class="action" id="codex-auths-paste-details" style="border-bottom:1px solid var(--border); background:var(--panel-2);">',
    '    <summary style="cursor:pointer; padding:12px 20px; color:var(--muted); font-size:12px; user-select:none;">Paste OAuth JSON</summary>',
    '    <div class="paste-body" style="display:grid; gap:10px; padding:0 20px 16px;">',
    '      <input id="codex-auths-paste-name" type="text" placeholder="profile name" autocomplete="off" />',
    '      <textarea id="codex-auths-paste-json" placeholder=\'{"tokens": {"access_token": "...", "refresh_token": "...", "expires": 1735689600, "account_id": "..."}}\' rows="6"></textarea>',
    '      <div class="button-row"><button class="ghost" id="codex-auths-paste-save" type="button">Save JSON as profile</button></div>',
    '      <small style="color:var(--muted);">Tokens stay in <code>~/.shimex/codex-auths.json</code> on this machine. Shimex never logs them.</small>',
    '    </div>',
    '  </details>',
    '  <div class="auth-profiles" id="codex-auths-rows"><div class="auth-empty">Loading Codex profiles…</div></div>',
    '</div>',
  ].join('\n');
}

export function codexAuthsRuntimeHelpers() {
  return [
    "    const codexAuthsEls = {};",
    "    const codexAuthsState = { profiles: [], defaultProfile: '', path: '', usage: {}, usageLoading: {} };",
    "    function initCodexAuths() {",
    "      codexAuthsEls.rows = document.getElementById('codex-auths-rows');",
    "      codexAuthsEls.path = document.getElementById('codex-auths-path');",
    "      codexAuthsEls.status = document.getElementById('codex-auths-status');",
    "      codexAuthsEls.title = document.getElementById('codex-auths-title');",
    "      codexAuthsEls.deviceName = document.getElementById('codex-auths-device-name');",
    "      codexAuthsEls.deviceStart = document.getElementById('codex-auths-device-start');",
    "      codexAuthsEls.pasteName = document.getElementById('codex-auths-paste-name');",
    "      codexAuthsEls.pasteJson = document.getElementById('codex-auths-paste-json');",
    "      codexAuthsEls.pasteSave = document.getElementById('codex-auths-paste-save');",
    "      if (codexAuthsEls.deviceStart) codexAuthsEls.deviceStart.addEventListener('click', startCodexDeviceLogin);",
    "      if (codexAuthsEls.pasteSave) codexAuthsEls.pasteSave.addEventListener('click', savePastedCodexAuth);",
    "      codexAuthsEls.refresh = document.getElementById('codex-auths-refresh');",
    "      if (codexAuthsEls.refresh) codexAuthsEls.refresh.addEventListener('click', refreshCodexUsage);",
    "      loadCodexAuths();",
    "    }",
    "    async function startCodexDeviceLogin() {",
    "      const profile = (codexAuthsEls.deviceName.value || '').trim();",
    "      try {",
    "        const response = await fetch('/api/codex-auths/start-device', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(profile ? { profile: profile } : {}) });",
    "        const result = await parseJson(response);",
    "        if (!response.ok || !result.device || !result.device.id) { toast('Codex device login failed to start', (result && result.error) || 'missing device id', 'err'); return; }",
    "        window.open('/admin/codex-auth/device?id=' + encodeURIComponent(result.device.id), '_blank', 'noopener');",
    "        toast('Codex device login started', result.device.userCode, 'ok');",
    "      } catch (error) { toast('Codex device login failed to start', String((error && error.message) || error), 'err'); }",
    "    }",
    "    async function savePastedCodexAuth() {",
    "      const profile = (codexAuthsEls.pasteName.value || '').trim(); const text = codexAuthsEls.pasteJson.value.trim();",
    "      if (!profile) { toast('Save failed', 'Enter a profile name first.', 'err'); return; } if (!text) { toast('Save failed', 'Paste OAuth JSON first.', 'err'); return; }",
    "      let payload; try { payload = JSON.parse(text); } catch (error) { toast('Save failed', 'Invalid JSON: ' + (error && error.message || error), 'err'); return; }",
    "      try {",
    "        const response = await fetch('/api/codex-auths', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: profile, auth_json: text, label: payload && payload.label || profile }) });",
    "        const result = await parseJson(response); if (!response.ok) { toast('Save failed', (result && result.error) || ('HTTP ' + response.status), 'err'); return; }",
    "        toast('Saved', result.profile && result.profile.name || profile, 'ok'); codexAuthsEls.pasteJson.value = ''; await loadCodexAuths();",
    "      } catch (error) { toast('Save failed', String((error && error.message) || error), 'err'); }",
    "    }",
    "    async function fetchCodexUsage(name) {",
    "      try {",
    "        var usageResponse = await fetch('/api/codex-auths/' + encodeURIComponent(name) + '/usage');",
    "        var usage = await parseJson(usageResponse);",
    "        if (!usageResponse.ok) return { error: (usage && usage.error) || ('HTTP ' + usageResponse.status) };",
    "        var creditsResponse = await fetch('/api/codex-auths/' + encodeURIComponent(name) + '/credits');",
    "        var credits = await parseJson(creditsResponse);",
    "        if (creditsResponse.ok) usage.resetCredits = credits; else usage.resetCreditsError = (credits && credits.error) || ('HTTP ' + creditsResponse.status);",
    "        return usage;",
    "      } catch (error) { return { error: String((error && error.message) || error) }; }",
    "    }",
    "    function codexFmtDateTime(value) { if (!value) return '—'; var date = new Date(value); if (Number.isNaN(date.getTime())) return value; return date.toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }); }",
    "    function codexFmtDuration(seconds) { var total = Math.max(0, Number(seconds) || 0); var h = Math.floor(total / 3600); var m = Math.floor((total % 3600) / 60); return h + 'h ' + String(m).padStart(2, '0') + 'm'; }",
    "    function codexFmtCountdown(seconds) { var total = Math.max(0, Number(seconds) || 0); var d = Math.floor(total / 86400); var h = Math.floor((total % 86400) / 3600); var m = Math.floor((total % 3600) / 60); if (d > 0) return d + 'd ' + h + 'h ' + m + 'm left'; if (h > 0) return h + 'h ' + m + 'm left'; return m + 'm left'; }",
    "    function codexResetLabel(resetAtIso, resetAfterSeconds) { var parts = []; if (resetAtIso) parts.push('resets ' + codexFmtDateTime(resetAtIso)); if (resetAfterSeconds != null && resetAfterSeconds >= 0) parts.push(codexFmtCountdown(resetAfterSeconds)); return parts.join(' · '); }",
    "    function codexUsageColor(remaining) { if (remaining < 10) return 'var(--danger)'; if (remaining < 30) return 'var(--warn)'; return 'var(--ok)'; }",
    "    function codexRingHtml(pct, color) {",
    "      var r = 18, c = 2 * Math.PI * r; var clamped = Math.max(0, Math.min(100, Math.round(pct || 0))); var offset = c * (1 - clamped / 100);",
    "      return '<div class=\"usage-ring\" style=\"--usage-color:' + color + '\"><svg viewBox=\"0 0 44 44\"><circle class=\"ring-bg\" cx=\"22\" cy=\"22\" r=\"' + r + '\"></circle><circle class=\"ring-fill\" cx=\"22\" cy=\"22\" r=\"' + r + '\" stroke-dasharray=\"' + c.toFixed(2) + '\" stroke-dashoffset=\"' + offset.toFixed(2) + '\"></circle></svg><span class=\"ring-pct\">' + clamped + '%</span></div>';",
    "    }",
    "    function codexTrackClass(remaining) { if (remaining < 10) return ' danger'; if (remaining < 30) return ' warn'; return ''; }",
    "    function codexUsageLane(label, remaining, resetLabel) {",
    "      var safe = Math.max(0, Math.min(100, Math.round(remaining || 0))); var color = codexUsageColor(safe);",
    "      return '<div class=\"usage-lane\" style=\"--usage-color:' + color + '\">' + codexRingHtml(safe, color) + '<div class=\"usage-lane-body\"><div class=\"usage-lane-head\"><span class=\"usage-lane-label\">' + escapeHtml(label) + '</span><span class=\"usage-lane-value\">' + escapeHtml(String(safe) + '% remaining') + '</span><span class=\"usage-lane-reset\">' + escapeHtml(resetLabel || '') + '</span></div><div class=\"usage-track\"><div class=\"usage-track-fill' + codexTrackClass(safe) + '\" style=\"width:' + safe + '%\"></div></div></div></div>';",
    "    }",
    "    function codexResetCreditsHtml(usage) {",
    "      var resetCredits = usage && usage.resetCredits;",
    "      if (!resetCredits) return usage && usage.resetCreditsError ? '<div class=\"usage-reset-credits error\">Credit expirations unavailable: ' + escapeHtml(usage.resetCreditsError) + '</div>' : '';",
    "      var available = resetCredits.available == null ? '?' : resetCredits.available;",
    "      var total = resetCredits.totalEarned == null ? '?' : resetCredits.totalEarned;",
    "      var rows = Array.isArray(resetCredits.credits) ? resetCredits.credits : [];",
    "      var body = '<div class=\"usage-reset-credits\"><div class=\"usage-reset-credits-head\"><span>Available reset credits: ' + escapeHtml(available) + '</span><span>Total earned: ' + escapeHtml(total) + '</span></div>';",
    "      if (rows.length) body += '<div class=\"usage-credit-expirations\">' + rows.map(function (credit) { var status = credit && credit.status ? ' [' + credit.status + ']' : ''; return '<div class=\"usage-credit-expiration\">Credit expires: ' + escapeHtml(codexFmtDateTime(credit && credit.expiresAt)) + escapeHtml(status) + '</div>'; }).join('') + '</div>';",
    "      else body += '<div class=\"usage-credit-expirations muted\">No credit expirations returned.</div>';",
    "      return body + '</div>';",
    "    }",
    "    function codexStatusCell(profile) { var cls = profile.available === false ? 'text' : (profile.tokenExpired ? 'danger' : ''); var label = profile.available === false ? 'Unavailable' : (profile.tokenExpired ? 'Expired' : 'Connected'); return '<span class=\"auth-status ' + cls + '\">' + escapeHtml(label) + '</span>'; }",
    "    function codexProfileCell(profile) {",
    "      var tags = ''; if (profile.isDefault) tags += '<span class=\"profile-chip default\">default</span>'; if (profile.readOnly) tags += '<span class=\"profile-chip readonly\">read-only</span>'; if (tags) tags = '<div class=\"profile-tags\">' + tags + '</div>';",
    "      var note = profile.readOnly ? '<div class=\"profile-note\">Managed by Codex</div>' : (profile.isDefault ? '<div class=\"profile-note\">active profile</div>' : '');",
    "      return codexStatusCell(profile) + '<div class=\"profile-name\">' + escapeHtml(profile.name.replace('-', '+')) + '</div>' + (profile.label && profile.label !== profile.name ? '<div class=\"profile-label\">' + escapeHtml(profile.label) + '</div>' : '') + tags + note;",
    "    }",
    "    function codexTokenCell(profile) {",
    "      if (!profile.expiresAt) return '<span class=\"token-pill unknown\">unknown</span>';",
    "      var cls = profile.tokenExpired ? 'danger' : ''; var label = profile.tokenExpired ? 'expired' : 'valid'; var prefix = profile.tokenExpired ? 'expired ' : 'until ';",
    "      return '<div class=\"token-row\"><span class=\"token-pill ' + cls + '\">' + escapeHtml(label) + '</span><span class=\"token-detail\">' + escapeHtml(prefix + codexFmtDateTime(profile.expiresAt)) + '</span></div>';",
    "    }",
    "    function codexUsageCell(profile) {",
    "      if (codexAuthsState.usageLoading[profile.name]) return '<span class=\"usage-loading\">loading</span>';",
    "      var usage = codexAuthsState.usage[profile.name];",
    "      if (!usage) return '<button class=\"ghost\" data-usage=\"' + escapeHtml(profile.name) + '\" type=\"button\" style=\"font-size:12px;padding:6px 12px;\">Probe usage</button>';",
    "      if (usage.error) return '<div class=\"usage-empty\"><button class=\"ghost\" data-usage=\"' + escapeHtml(profile.name) + '\" type=\"button\" title=\"' + escapeHtml(usage.error) + '\" style=\"font-size:12px;padding:6px 12px;\">Retry</button><div style=\"margin-top:6px;\">' + escapeHtml(usage.error) + '</div></div>';",
    "      var color = usage.planType === 'plus' ? '#b36cff' : '#4797ff';",
    "      var lanes = '';",
    "      if (usage.primaryWindow) { var pw = usage.primaryWindow; lanes += codexUsageLane('5h window remaining', pw.remainingPercent, codexResetLabel(pw.resetAtIso, pw.resetAfterSeconds)); }",
    "      if (usage.secondaryWindow) { var sw = usage.secondaryWindow; lanes += codexUsageLane('Weekly window remaining', sw.remainingPercent, codexResetLabel(sw.resetAtIso, sw.resetAfterSeconds)); }",
    "      if (!lanes) return '<span class=\"usage-empty\">no usage windows</span>';",
    "      var planRow = '<div class=\"usage-plan-row\">' + (usage.planType ? '<span class=\"usage-plan-badge\" style=\"--usage-color:' + color + '\">' + escapeHtml(usage.planType) + '</span>' : '');",
    "      var balance = usage.credits && usage.credits.balance !== '' ? usage.credits.balance : (usage.resetCreditsAvailable == null ? '?' : usage.resetCreditsAvailable);",
    "      planRow += '<span class=\"usage-credits-chip\">credits: ' + escapeHtml(balance) + '</span></div>';",
    "      return planRow + '<div class=\"usage-graph\">' + lanes + '</div>' + codexResetCreditsHtml(usage);",
    "    }",
    "    function codexActionCell(profile) {",
    "      if (profile.readOnly) return '<div class=\"auth-actions\"><span class=\"auth-action-label\">Managed by Codex</span></div>';",
    "      var renew = profile.canRenew ? '<button data-renew=\"' + escapeHtml(profile.name) + '\" type=\"button\">Refresh</button>' : '<button data-reauth=\"' + escapeHtml(profile.name) + '\" type=\"button\" title=\"This profile has no refresh token. Sign in again to enable refresh.\">Re-authenticate</button>';",
    "      return '<div class=\"auth-actions\">' + [renew, '<button data-rename=\"' + escapeHtml(profile.name) + '\" type=\"button\">Rename</button>', '<button data-use=\"' + escapeHtml(profile.name) + '\" type=\"button\"' + (profile.isDefault ? ' disabled' : '') + '>' + (profile.isDefault ? 'Default' : 'Make default') + '</button>', '<button class=\"danger\" data-remove=\"' + escapeHtml(profile.name) + '\" type=\"button\">Disconnect</button>'].join('') + '</div>';",
    "    }",
    "    function codexProfileRow(profile) {",
    "      return '<div class=\"auth-profile\" data-profile=\"' + escapeHtml(profile.name) + '\">' +",
    "        '<div class=\"auth-profile-identity\">' + codexProfileCell(profile) + '</div>' +",
    "        '<div class=\"auth-profile-usage\">' + codexUsageCell(profile) + '</div>' +",
    "        '<div class=\"auth-profile-side\">' + codexTokenCell(profile) + '<div class=\"updated-row\">updated ' + escapeHtml(codexFmtDateTime(profile.updatedAt)) + '</div>' + codexActionCell(profile) + '</div>' +",
    "        '</div>';",
    "    }",
    "    function setCodexRefreshBusy(busy) { if (!codexAuthsEls.refresh) return; codexAuthsEls.refresh.disabled = busy; }",
    "    async function refreshCodexUsage() { if (!codexAuthsState.profiles.length) return; setCodexRefreshBusy(true); var names = codexAuthsState.profiles.map(function (p) { return p.name; }); codexAuthsState.usageLoading = {}; names.forEach(function (n) { codexAuthsState.usageLoading[n] = true; }); renderCodexAuths(); await Promise.all(names.map(function (n) { return fetchCodexUsage(n).then(function (u) { codexAuthsState.usage[n] = u; }).catch(function (e) { codexAuthsState.usage[n] = { error: String((e && e.message) || e) }; }).finally(function () { delete codexAuthsState.usageLoading[n]; }); })); setCodexRefreshBusy(false); renderCodexAuths(); }",
    "    async function loadOneCodexUsage(name) { if (!name || codexAuthsState.usageLoading[name]) return; codexAuthsState.usageLoading[name] = true; renderCodexAuths(); codexAuthsState.usage[name] = await fetchCodexUsage(name); delete codexAuthsState.usageLoading[name]; renderCodexAuths(); }",
    "    function autoLoadCodexUsage() { (codexAuthsState.profiles || []).forEach(function (profile) { if (profile && profile.name && !codexAuthsState.usage[profile.name] && !codexAuthsState.usageLoading[profile.name]) loadOneCodexUsage(profile.name); }); }",
    "    function renderCodexAuths() {",
    "      if (codexAuthsState.path && codexAuthsEls.path) codexAuthsEls.path.textContent = codexAuthsState.path;",
    "      if (codexAuthsEls.title) { var countEl = codexAuthsEls.title.querySelector('.auth-count'); if (countEl) countEl.textContent = codexAuthsState.profiles.length ? '(' + codexAuthsState.profiles.length + ')' : ''; }",
    "      if (codexAuthsEls.status) codexAuthsEls.status.innerHTML = codexAuthsState.profiles.length + ' profile' + (codexAuthsState.profiles.length === 1 ? '' : 's') + ' persisted in <code id=\"codex-auths-path\">' + escapeHtml(codexAuthsState.path || '~/.shimex/codex-auths.json') + '</code>';",
    "      if (!codexAuthsState.profiles.length) { codexAuthsEls.rows.innerHTML = '<div class=\"auth-empty\">No Codex auth profiles yet. Use “Sign in” above to add one.</div>'; return; }",
    "      codexAuthsEls.rows.innerHTML = codexAuthsState.profiles.map(codexProfileRow).join('');",
    "      codexAuthsEls.rows.querySelectorAll('button[data-usage]').forEach(function (button) { button.addEventListener('click', async function () { await loadOneCodexUsage(this.getAttribute('data-usage')); }); });",
    "      codexAuthsEls.rows.querySelectorAll('button[data-renew]').forEach(function (button) { button.addEventListener('click', async function () { var name = this.getAttribute('data-renew'); try { this.disabled = true; this.textContent = 'Renewing…'; var response = await fetch('/api/codex-auths/' + encodeURIComponent(name) + '/renew', { method: 'POST' }); var result = await parseJson(response); if (!response.ok) { toast('Renew failed', (result && result.error) || ('HTTP ' + response.status), 'err'); return; } delete codexAuthsState.usage[name]; toast('Renewed Codex profile', name, 'ok'); await loadCodexAuths(); } catch (error) { toast('Renew failed', String((error && error.message) || error), 'err'); } }); });",
    "      codexAuthsEls.rows.querySelectorAll('button[data-reauth]').forEach(function (button) { button.addEventListener('click', function () { var name = this.getAttribute('data-reauth'); if (codexAuthsEls.deviceName) codexAuthsEls.deviceName.value = name || ''; toast('Re-authentication needed', 'Sign in again to replace this profile with a refresh token.', 'err'); if (codexAuthsEls.deviceStart) codexAuthsEls.deviceStart.focus(); }); });",
    "      codexAuthsEls.rows.querySelectorAll('button[data-rename]').forEach(function (button) { button.addEventListener('click', async function () { var name = this.getAttribute('data-rename'); var next = window.prompt('Rename Codex auth profile “' + name + '” to:', name); if (!next || next === name) return; try { var response = await fetch('/api/codex-auths/' + encodeURIComponent(name) + '/rename', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: next }) }); var result = await parseJson(response); if (!response.ok) { toast('Rename failed', (result && result.error) || ('HTTP ' + response.status), 'err'); return; } if (codexAuthsState.usage[name]) { codexAuthsState.usage[result.to || next] = codexAuthsState.usage[name]; delete codexAuthsState.usage[name]; } toast('Renamed profile', name + ' → ' + (result.to || next), 'ok'); await loadCodexAuths(); } catch (error) { toast('Rename failed', String((error && error.message) || error), 'err'); } }); });",
    "      codexAuthsEls.rows.querySelectorAll('button[data-use]').forEach(function (button) { button.addEventListener('click', async function () { var name = this.getAttribute('data-use'); try { var response = await fetch('/api/codex-auths/' + encodeURIComponent(name) + '/use', { method: 'POST' }); var result = await parseJson(response); if (!response.ok) { toast('Use failed', (result && result.error) || ('HTTP ' + response.status), 'err'); return; } toast('Default profile', result.defaultProfile || name, 'ok'); await loadCodexAuths(); } catch (error) { toast('Use failed', String((error && error.message) || error), 'err'); } }); });",
    "      codexAuthsEls.rows.querySelectorAll('button[data-remove]').forEach(function (button) { button.addEventListener('click', async function () { var name = this.getAttribute('data-remove'); if (!window.confirm('Disconnect Codex auth profile “' + name + '”?')) return; try { var response = await fetch('/api/codex-auths/' + encodeURIComponent(name), { method: 'DELETE' }); var result = await parseJson(response); if (!response.ok) { toast('Disconnect failed', (result && result.error) || ('HTTP ' + response.status), 'err'); return; } toast('Disconnected', name, 'ok'); await loadCodexAuths(); } catch (error) { toast('Disconnect failed', String((error && error.message) || error), 'err'); } }); });",
    "    }",
    "    async function loadCodexAuths() { try { var response = await fetch('/api/codex-auths'); var result = await parseJson(response); if (!response.ok) { codexAuthsEls.rows.innerHTML = '<div class=\"auth-empty\">Could not load Codex auths: ' + ((result && result.error) || ('HTTP ' + response.status)) + '</div>'; return; } codexAuthsState.profiles = result.profiles || []; codexAuthsState.defaultProfile = result.defaultProfile || ''; codexAuthsState.path = result.path || ''; renderCodexAuths(); autoLoadCodexUsage(); } catch (error) { codexAuthsEls.rows.innerHTML = '<div class=\"auth-empty\">Could not load Codex auths: ' + ((error && error.message) || error) + '</div>'; } }",
  ].join('\n');
}
