export function cursorAuthsCard() {
  return [
    '<div class="auth-page span-12" id="cursor-auths-panel">',
    '  <section class="auth-shell">',
    '    <div class="auth-toolbar">',
    '      <div class="auth-toolbar-copy">',
    '        <div class="auth-kicker">Session <span id="cursor-auths-title" class="auth-count"></span></div>',
    '        <p id="cursor-auths-status" class="auth-meta">checking Cursor Agent session…</p>',
    '      </div>',
    '      <button class="auth-refresh" id="cursor-auths-refresh" type="button" title="Re-probe Cursor session"><span class="spin"></span>Refresh</button>',
    '    </div>',
    '    <div class="auth-signin" id="cursor-auths-actions">',
    '      <div class="auth-signin-copy">',
    '        <div class="auth-signin-icon" aria-hidden="true">C</div>',
    '        <div>',
    '          <div class="auth-signin-title">Cursor subscription</div>',
    '          <div class="auth-signin-desc">Shimex uses Cursor Agent’s own browser login. Your Cursor credentials stay in Cursor’s local session; Shimex only checks the CLI status and forwards requests through it.</div>',
    '        </div>',
    '      </div>',
    '      <div class="auth-signin-controls">',
    '        <button class="ghost" id="cursor-auths-login" type="button">Sign in with Cursor</button>',
    '      </div>',
    '    </div>',
    '    <div class="auth-profiles" id="cursor-auths-rows"><div class="auth-empty">Loading Cursor session…</div></div>',
    '  </section>',
    '</div>',
  ].join('\n');
}

export function cursorAuthsRuntimeHelpers() {
  return [
    "    const cursorAuthsEls = {};",
    "    const cursorAuthsState = { connected: false, bypassed: false, agentBin: '', reason: '', message: '', login: null, busy: false };",
    "    function initCursorAuths() {",
    "      cursorAuthsEls.rows = document.getElementById('cursor-auths-rows');",
    "      cursorAuthsEls.path = document.getElementById('cursor-auths-path');",
    "      cursorAuthsEls.status = document.getElementById('cursor-auths-status');",
    "      cursorAuthsEls.title = document.getElementById('cursor-auths-title');",
    "      cursorAuthsEls.refresh = document.getElementById('cursor-auths-refresh');",
    "      cursorAuthsEls.login = document.getElementById('cursor-auths-login');",
    "      if (cursorAuthsEls.refresh) cursorAuthsEls.refresh.addEventListener('click', refreshCursorAuths);",
    "      if (cursorAuthsEls.login) cursorAuthsEls.login.addEventListener('click', startCursorLogin);",
    "      loadCursorAuths();",
    "    }",
    "    function setCursorAuthBusy(busy) {",
    "      cursorAuthsState.busy = !!busy;",
    "      if (cursorAuthsEls.login) { cursorAuthsEls.login.disabled = !!busy; cursorAuthsEls.login.textContent = busy ? 'Waiting for browser login…' : (cursorAuthsState.connected ? 'Sign in again' : 'Sign in with Cursor'); }",
    "      if (cursorAuthsEls.refresh) cursorAuthsEls.refresh.disabled = !!busy;",
    "    }",
    "    function cursorAuthStatusText() {",
    "      if (cursorAuthsState.connected) return cursorAuthsState.bypassed ? 'model visibility enabled by config' : 'Cursor Agent session connected';",
    "      return cursorAuthsState.message || 'no local Cursor Agent session';",
    "    }",
    "    function cursorProfileRow() {",
    "      if (!cursorAuthsState.connected) return '<div class=\"auth-empty\">' + escapeHtml(cursorAuthsState.message || 'No Cursor session found. Use “Sign in with Cursor” to open the browser login.') + '</div>';",
    "      var label = cursorAuthsState.bypassed ? 'auth bypass enabled by config' : 'external Cursor Agent session';",
    "      var agent = cursorAuthsState.agentBin ? '<div class=\"profile-note\">CLI <code>' + escapeHtml(cursorAuthsState.agentBin) + '</code></div>' : '';",
    "      return '<div class=\"auth-profile\">' +",
    "        '<div class=\"auth-profile-identity\">' +",
    "          '<span class=\"auth-status\">' + (cursorAuthsState.bypassed ? 'Available' : 'Connected') + '</span>' +",
    "          '<div class=\"profile-name\">Cursor subscription</div>' +",
    "          '<div class=\"profile-label\">Cursor account models via Cursor Agent</div>' +",
    "          '<div class=\"profile-tags\"><span class=\"profile-chip\">' + escapeHtml(label) + '</span><span class=\"profile-chip\">text input</span></div>' +",
    "          agent +",
    "        '</div>' +",
    "        '<div class=\"auth-profile-usage\"><div class=\"usage-empty\">Cursor subscription usage is managed by Cursor.</div></div>' +",
    "        '<div class=\"auth-profile-side\"><div class=\"token-row\"><span class=\"token-pill\">ready</span><div class=\"token-detail\">local CLI session</div></div><div class=\"auth-actions\"><button type=\"button\" data-cursor-login=\"1\">Sign in again</button></div></div>' +",
    "      '</div>';",
    "    }",
    "    function renderCursorAuths() {",
    "      if (!cursorAuthsEls.rows) return;",
    "      if (cursorAuthsEls.title) cursorAuthsEls.title.innerHTML = cursorAuthsState.connected ? '<span class=\"auth-count\">connected</span>' : '';",
    "      if (cursorAuthsEls.status) { var statusText = escapeHtml(cursorAuthStatusText()); cursorAuthsEls.status.innerHTML = statusText + (cursorAuthsState.agentBin ? ' via <code id=\"cursor-auths-path\">' + escapeHtml(cursorAuthsState.agentBin) + '</code>' : ''); }",
    "      cursorAuthsEls.path = document.getElementById('cursor-auths-path');",
    "      cursorAuthsEls.rows.innerHTML = cursorProfileRow();",
    "      cursorAuthsEls.rows.querySelectorAll('button[data-cursor-login]').forEach(function (button) { button.addEventListener('click', startCursorLogin); });",
    "    }",
    "    async function loadCursorAuths() {",
    "      if (!cursorAuthsEls.rows) return;",
    "      try {",
    "        var response = await fetch('/api/cursor-auth');",
    "        var result = await parseJson(response);",
    "        if (!response.ok) throw new Error((result && result.error) || ('HTTP ' + response.status));",
    "        cursorAuthsState.connected = !!result.connected;",
    "        cursorAuthsState.bypassed = !!result.bypassed;",
    "        cursorAuthsState.agentBin = result.agentBin || '';",
    "        cursorAuthsState.reason = result.reason || '';",
    "        cursorAuthsState.message = result.message || '';",
    "        renderCursorAuths();",
    "      } catch (error) {",
    "        cursorAuthsState.connected = false;",
    "        cursorAuthsState.message = 'Could not load Cursor auth: ' + String((error && error.message) || error);",
    "        renderCursorAuths();",
    "      }",
    "    }",
    "    async function refreshCursorModels() {",
    "      var response = await fetch('/api/cursor-auth/refresh', { method: 'POST' });",
    "      var result = await parseJson(response);",
    "      if (!response.ok) throw new Error((result && (result.message || result.error)) || ('HTTP ' + response.status));",
    "      return result;",
    "    }",
    "    async function refreshCursorAuths() {",
    "      await loadCursorAuths();",
    "      if (!cursorAuthsState.connected) return;",
    "      try {",
    "        var result = await refreshCursorModels();",
    "        if (typeof load === 'function') await load();",
    "        toast('Cursor models refreshed', result.message || 'The Cursor model list is available in the picker.', 'ok');",
    "      } catch (error) {",
    "        toast('Cursor model refresh failed', String((error && error.message) || error), 'error');",
    "      }",
    "    }",
    "    async function startCursorLogin() {",
    "      if (cursorAuthsState.busy) return;",
    "      setCursorAuthBusy(true);",
    "      try {",
    "        var response = await fetch('/api/cursor-auth/login', { method: 'POST' });",
    "        var result = await parseJson(response);",
    "        if (!response.ok) throw new Error((result && (result.message || result.error)) || ('HTTP ' + response.status));",
    "        cursorAuthsState.login = result.login || null;",
    "        toast('Cursor login started', 'Finish the Cursor login in your browser on this host.', 'ok');",
    "        if (cursorAuthsState.login && cursorAuthsState.login.id) await pollCursorLogin(cursorAuthsState.login.id);",
    "        else await loadCursorAuths();",
    "      } catch (error) {",
    "        toast('Cursor login unavailable', String((error && error.message) || error), 'error');",
    "        await loadCursorAuths();",
    "      } finally {",
    "        setCursorAuthBusy(false);",
    "        renderCursorAuths();",
    "      }",
    "    }",
    "    async function pollCursorLogin(loginId) {",
    "      for (var attempt = 0; attempt < 120; attempt += 1) {",
    "        await new Promise(function (resolve) { window.setTimeout(resolve, 1000); });",
    "        var response = await fetch('/api/cursor-auth/login/' + encodeURIComponent(loginId));",
    "        var result = await parseJson(response);",
    "        if (!response.ok) throw new Error((result && result.error) || ('HTTP ' + response.status));",
    "        cursorAuthsState.login = result.login || cursorAuthsState.login;",
    "        cursorAuthsState.connected = !!result.connected;",
    "        cursorAuthsState.bypassed = !!result.bypassed;",
    "        cursorAuthsState.message = result.message || cursorAuthsState.message;",
    "        renderCursorAuths();",
    "        if (cursorAuthsState.connected) {",
    "          var modelRefresh = null;",
    "          try { modelRefresh = await refreshCursorModels(); } catch (error) { /* auth still succeeded; surface refresh on the panel */ }",
    "          toast('Cursor connected', modelRefresh && modelRefresh.message ? modelRefresh.message : 'Cursor account models are now available to Shimex.', 'ok');",
    "          if (typeof load === 'function') await load();",
    "          return;",
    "        }",
    "        var status = cursorAuthsState.login && cursorAuthsState.login.status;",
    "        if (status && status !== 'pending') {",
    "          toast('Cursor login did not complete', result.message || 'Finish the browser login and try again.', 'error');",
    "          await loadCursorAuths();",
    "          return;",
    "        }",
    "      }",
    "      toast('Cursor login timed out', 'Finish the browser login and refresh this panel.', 'error');",
    "      await loadCursorAuths();",
    "    }",
  ].join("\n");
}
