export function grokAuthsCard() {
  return [
    '<div class="auth-page span-12" id="grok-auths-panel">',
    '  <section class="auth-shell">',
    '    <div class="auth-toolbar">',
    '      <div class="auth-toolbar-copy">',
    '        <div class="auth-kicker">Session <span id="grok-auths-title" class="auth-count"></span></div>',
    '        <p id="grok-auths-status" class="auth-meta">subscription session from <code id="grok-auths-path">~/.grok/auth.json</code></p>',
    '      </div>',
    '      <button class="auth-refresh" id="grok-auths-refresh" type="button" title="Re-probe Grok usage"><span class="spin"></span>Refresh</button>',
    '    </div>',
    '    <div class="auth-signin" id="grok-auths-actions">',
    '      <div class="auth-signin-copy">',
    '        <div class="auth-signin-icon" aria-hidden="true">G</div>',
    '        <div>',
    '          <div class="auth-signin-title">Grok CLI session</div>',
    '          <div class="auth-signin-desc">Shimex reads the local Grok subscription session from <code>~/.grok/auth.json</code>. Run <code>grok login</code> on this host, then refresh usage here.</div>',
    '        </div>',
    '      </div>',
    '      <div class="auth-signin-controls">',
    '        <button class="ghost" id="grok-auths-open-billing" type="button">Open billing</button>',
    '      </div>',
    '    </div>',
    '    <div class="auth-profiles" id="grok-auths-rows"><div class="auth-empty">Loading Grok session…</div></div>',
    '  </section>',
    '</div>',
  ].join('\n');
}

export function grokAuthsRuntimeHelpers() {
  return [
    "    const grokAuthsEls = {};",
    "    const grokAuthsState = { session: null, path: '', usage: null, usageLoading: false, connected: false };",
    "    function initGrokAuths() {",
    "      grokAuthsEls.rows = document.getElementById('grok-auths-rows');",
    "      grokAuthsEls.path = document.getElementById('grok-auths-path');",
    "      grokAuthsEls.status = document.getElementById('grok-auths-status');",
    "      grokAuthsEls.title = document.getElementById('grok-auths-title');",
    "      grokAuthsEls.refresh = document.getElementById('grok-auths-refresh');",
    "      grokAuthsEls.openBilling = document.getElementById('grok-auths-open-billing');",
    "      if (grokAuthsEls.refresh) grokAuthsEls.refresh.addEventListener('click', refreshGrokUsage);",
    "      if (grokAuthsEls.openBilling) grokAuthsEls.openBilling.addEventListener('click', function () { window.open('https://grok.com/?_s=billing', '_blank', 'noopener'); });",
    "      loadGrokAuths();",
    "    }",
    "    function setGrokRefreshBusy(busy) {",
    "      if (!grokAuthsEls.refresh) return;",
    "      grokAuthsEls.refresh.disabled = !!busy;",
    "    }",
    "    function grokFmtDateTime(value) { if (!value) return '—'; var date = new Date(value); if (Number.isNaN(date.getTime())) return value; return date.toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }); }",
    "    function grokUsageColor(remaining) { if (remaining < 10) return 'var(--danger)'; if (remaining < 30) return 'var(--warn)'; return 'var(--ok)'; }",
    "    function grokRingHtml(pct, color) {",
    "      var r = 18, c = 2 * Math.PI * r; var clamped = Math.max(0, Math.min(100, Math.round(pct || 0))); var offset = c * (1 - clamped / 100);",
    "      return '<div class=\"usage-ring\" style=\"--usage-color:' + color + '\"><svg viewBox=\"0 0 44 44\"><circle class=\"ring-bg\" cx=\"22\" cy=\"22\" r=\"' + r + '\"></circle><circle class=\"ring-fill\" cx=\"22\" cy=\"22\" r=\"' + r + '\" stroke-dasharray=\"' + c.toFixed(2) + '\" stroke-dashoffset=\"' + offset.toFixed(2) + '\"></circle></svg><span class=\"ring-pct\">' + clamped + '%</span></div>';",
    "    }",
    "    function grokTrackClass(remaining) { if (remaining < 10) return ' danger'; if (remaining < 30) return ' warn'; return ''; }",
    "    function grokUsageLane(label, remaining, resetLabel) {",
    "      var safe = Math.max(0, Math.min(100, Math.round(remaining == null ? 0 : remaining))); var color = grokUsageColor(safe);",
    "      return '<div class=\"usage-lane\" style=\"--usage-color:' + color + '\">' + grokRingHtml(safe, color) + '<div class=\"usage-lane-body\"><div class=\"usage-lane-head\"><span class=\"usage-lane-label\">' + escapeHtml(label) + '</span><span class=\"usage-lane-value\">' + escapeHtml(String(safe) + '% remaining') + '</span><span class=\"usage-lane-reset\">' + escapeHtml(resetLabel || '') + '</span></div><div class=\"usage-track\"><div class=\"usage-track-fill' + grokTrackClass(safe) + '\" style=\"width:' + safe + '%\"></div></div></div></div>';",
    "    }",
    "    function grokMoney(value) { if (value == null || !Number.isFinite(Number(value))) return '—'; return '$' + Number(value).toFixed(2); }",
    "    function grokUsageCell() {",
    "      if (grokAuthsState.usageLoading) return '<div class=\"usage-loading\">Probing Grok billing…</div>';",
    "      var usage = grokAuthsState.usage;",
    "      if (!usage) return '<div class=\"usage-empty\">Usage not loaded yet.</div>';",
    "      if (usage.error) return '<div class=\"usage-empty\">' + escapeHtml(usage.error) + '</div>';",
    "      var remaining = usage.remainingPercent;",
    "      var periodLabel = '';",
    "      if (usage.periodEnd) periodLabel = 'resets ' + grokFmtDateTime(usage.periodEnd);",
    "      else if (usage.periodType) periodLabel = String(usage.periodType);",
    "      var lanes = [grokUsageLane('Credits', remaining, periodLabel)];",
    "      (usage.products || []).forEach(function (product) {",
    "        lanes.push(grokUsageLane(product.product || 'Product', product.remainingPercent, ''));",
    "      });",
    "      var meta = [];",
    "      if (usage.periodStart || usage.periodEnd) meta.push('<div class=\"usage-reset-credits\"><div class=\"usage-reset-credits-head\"><span>' + escapeHtml((usage.periodType || 'period')) + '</span><span>' + escapeHtml(grokFmtDateTime(usage.periodStart)) + ' → ' + escapeHtml(grokFmtDateTime(usage.periodEnd)) + '</span></div></div>');",
    "      meta.push('<div class=\"usage-reset-credits\"><div class=\"usage-reset-credits-head\"><span>prepaid ' + escapeHtml(grokMoney(usage.prepaidBalance)) + '</span><span>on-demand used ' + escapeHtml(grokMoney(usage.onDemandUsed)) + ' / cap ' + escapeHtml(grokMoney(usage.onDemandCap)) + '</span></div></div>');",
    "      return '<div class=\"usage-graph\">' + lanes.join('') + meta.join('') + '</div>';",
    "    }",
    "    function grokTokenCell() {",
    "      var session = grokAuthsState.session;",
    "      if (!session) return '<div class=\"token-row\"><span class=\"token-pill unknown\">disconnected</span><div class=\"token-detail\">Run <code>grok login</code></div></div>';",
    "      var exp = session.expiresAt ? ('until ' + grokFmtDateTime(session.expiresAt)) : 'expiry unknown';",
    "      return '<div class=\"token-row\"><span class=\"token-pill\">valid</span><div class=\"token-detail\">' + escapeHtml(exp) + '</div><div class=\"updated-row\">session file</div></div>';",
    "    }",
    "    function grokProfileRow() {",
    "      if (!grokAuthsState.connected) {",
    "        return '<div class=\"auth-empty\">No Grok session found. Run <code>grok login</code> on this host, then refresh.</div>';",
    "      }",
    "      var session = grokAuthsState.session || {};",
    "      var name = session.email || session.userId || 'Grok session';",
    "      var tags = '<div class=\"profile-tags\"><span class=\"profile-chip\">external session</span></div>';",
    "      return '<div class=\"auth-profile\">' +",
    "        '<div class=\"auth-profile-identity\">' +",
    "          '<span class=\"auth-status\">Connected</span>' +",
    "          '<div class=\"profile-name\">' + escapeHtml(name) + '</div>' +",
    "          '<div class=\"profile-label\">Grok subscription session</div>' +",
    "          tags +",
    "          (session.teamId ? '<div class=\"profile-note\">team ' + escapeHtml(session.teamId) + '</div>' : '') +",
    "        '</div>' +",
    "        '<div class=\"auth-profile-usage\">' + grokUsageCell() + '</div>' +",
    "        '<div class=\"auth-profile-side\">' + grokTokenCell() +",
    "          '<div class=\"auth-actions\"><button type=\"button\" data-grok-usage=\"1\">Refresh usage</button>' +",
    "          '<button type=\"button\" data-grok-billing=\"1\">Manage billing</button></div>' +",
    "        '</div>' +",
    "      '</div>';",
    "    }",
    "    function renderGrokAuths() {",
    "      if (!grokAuthsEls.rows) return;",
    "      if (grokAuthsEls.path) grokAuthsEls.path.textContent = grokAuthsState.path || '~/.grok/auth.json';",
    "      if (grokAuthsEls.title) {",
    "        var count = grokAuthsState.connected ? 1 : 0;",
    "        grokAuthsEls.title.innerHTML = 'Grok session' + (count ? '<span class=\"auth-count\">(' + count + ')</span>' : '');",
    "      }",
    "      if (grokAuthsEls.status) {",
    "        grokAuthsEls.status.innerHTML = grokAuthsState.connected",
    "          ? 'subscription session from <code id=\"grok-auths-path\">' + escapeHtml(grokAuthsState.path || '~/.grok/auth.json') + '</code>'",
    "          : 'no local Grok session — run <code>grok login</code>';",
    "        grokAuthsEls.path = document.getElementById('grok-auths-path');",
    "      }",
    "      grokAuthsEls.rows.innerHTML = grokProfileRow();",
    "      grokAuthsEls.rows.querySelectorAll('button[data-grok-usage]').forEach(function (button) {",
    "        button.addEventListener('click', refreshGrokUsage);",
    "      });",
    "      grokAuthsEls.rows.querySelectorAll('button[data-grok-billing]').forEach(function (button) {",
    "        button.addEventListener('click', function () { window.open('https://grok.com/?_s=billing', '_blank', 'noopener'); });",
    "      });",
    "    }",
    "    async function fetchGrokUsage() {",
    "      try {",
    "        var response = await fetch('/api/grok-auth/usage');",
    "        var result = await parseJson(response);",
    "        if (!response.ok) return { error: (result && result.error) || ('HTTP ' + response.status) };",
    "        if (result.session) grokAuthsState.session = result.session;",
    "        if (result.connected != null) grokAuthsState.connected = !!result.connected;",
    "        return result.usage || result;",
    "      } catch (error) {",
    "        return { error: String((error && error.message) || error) };",
    "      }",
    "    }",
    "    async function refreshGrokUsage() {",
    "      if (!grokAuthsState.connected) { await loadGrokAuths(); if (!grokAuthsState.connected) return; }",
    "      setGrokRefreshBusy(true);",
    "      grokAuthsState.usageLoading = true;",
    "      renderGrokAuths();",
    "      grokAuthsState.usage = await fetchGrokUsage();",
    "      grokAuthsState.usageLoading = false;",
    "      setGrokRefreshBusy(false);",
    "      renderGrokAuths();",
    "    }",
    "    async function loadGrokAuths() {",
    "      try {",
    "        var response = await fetch('/api/grok-auth');",
    "        var result = await parseJson(response);",
    "        if (!response.ok) {",
    "          grokAuthsEls.rows.innerHTML = '<div class=\"auth-empty\">Could not load Grok auth: ' + escapeHtml((result && result.error) || ('HTTP ' + response.status)) + '</div>';",
    "          return;",
    "        }",
    "        grokAuthsState.connected = !!result.connected;",
    "        grokAuthsState.session = result.session || null;",
    "        grokAuthsState.path = result.path || '~/.grok/auth.json';",
    "        renderGrokAuths();",
    "        if (grokAuthsState.connected) refreshGrokUsage();",
    "      } catch (error) {",
    "        if (grokAuthsEls.rows) grokAuthsEls.rows.innerHTML = '<div class=\"auth-empty\">Could not load Grok auth: ' + escapeHtml(String((error && error.message) || error)) + '</div>';",
    "      }",
    "    }",
  ].join("\n");
}
