import { join } from "node:path";
import { expandHome } from "../../core/paths.js";

export function resolveCodexPaths(config) {
  const sourceApp = config.codex.sourceApp === "auto"
    ? "/Applications/Codex.app"
    : expandHome(config.codex.sourceApp);
  return {
    sourceApp,
    managedApp: expandHome(config.codex.managedAppPath || `~/Applications/${config.codex.managedAppName}.app`),
    profileHome: expandHome(config.codex.profileHome),
    userDataDir: expandHome(config.codex.userDataDir),
    catalogPath: join(expandHome(config.runtime.home), "codex-model-catalog.json"),
    configPath: join(expandHome(config.codex.profileHome), "config.toml"),
    authPath: join(expandHome(config.codex.profileHome), "auth.json"),
    globalStatePath: join(expandHome(config.codex.profileHome), ".codex-global-state.json"),
  };
}

export function codexConfigText(config, defaultModelSlug) {
  const paths = resolveCodexPaths(config);
  const providerName = "shimex";
  return [
    "# Generated by Shimex. This file belongs to Shimex's isolated Codex profile.",
    `model = "${tomlEscape(defaultModelSlug)}"`,
    `model_provider = "${providerName}"`,
    `model_catalog_json = "${tomlEscape(paths.catalogPath)}"`,
    "",
    `[model_providers.${providerName}]`,
    'name = "Shimex"',
    `base_url = "http://${config.runtime.host}:${config.runtime.port}/v1"`,
    'wire_api = "responses"',
    'experimental_bearer_token = "dummy"',
    "request_max_retries = 3",
    "stream_max_retries = 3",
    "stream_idle_timeout_ms = 600000",
    "",
  ].join("\n");
}

function tomlEscape(value) {
  return String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}
